Repository cse403-lemmeknow/lemmeknow, pull requests merged in 2024-02, with the labels that each got.

#62 Revise database API layer + added unit test (rough draft)
  backend/database.go
  backend/database_test.go
  backend/dbschema.go
Labels: enhancement

#54 Implement more backend API's.
  .github/workflows/backend.yml
  backend/README.md
  backend/api.go
  backend/database.go
  backend/database_test.go
  backend/dbschema.go
  backend/go.mod
  backend/go.sum
  backend/group.go
  backend/group_activity.go
  backend/group_availability.go
  backend/group_chat.go
  backend/group_poll.go
Labels: enhancement

#64 Implement chat and poll API's.
  backend/README.md
  backend/database.go
  backend/dbschema.go
  backend/group_chat.go
  backend/group_poll.go
  backend/main.go
Labels: enhancement

#65 Add third report.
  reports/20240207.md
Labels: documentation

#67 Add more backend tests.
  backend/database.go
  backend/group.go
  backend/group_chat.go
  backend/main.go
  backend/main_test.go
  backend/user.go
Labels: testing

#68 Add Terraform CI badge to README.
  README.md
Labels: documentation

#69 Allow DynamoDB unit tests to run in CI
  .github/workflows/backend.yml
  backend/database.go
  backend/database_test.go
  backend/dbschema.go
  backend/go.mod
  backend/go.sum
Labels: testing

#70 Skip database tests outside of CI
  backend/database_test.go
Labels: testing

#71 Finish developer guides.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  backend/README.md
  terraform/README.md
Labels: documentation

#72 Refine backend API's.
  backend/database.go
  backend/dbschema.go
  backend/group.go
  backend/group_activity.go
  backend/group_availability.go
  backend/group_poll.go
Labels: enhancement

#73 Check transaction error in `UpdateGroup`
  backend/database.go
Labels: bug

#80 Add tests for backend API's, fix discovered bugs.
  backend/README.md
  backend/database.go
  backend/group.go
  backend/group_availability.go
  backend/group_chat.go
  backend/group_poll.go
  backend/main_test.go
Labels: testing

#81 Test subtle backend API's.
  backend/README.md
  backend/group.go
  backend/group_activity.go
  backend/group_availability.go
  backend/group_chat.go
  backend/group_poll.go
  backend/main_test.go
Labels: enhancement, testing

#82 Implement backend notifications.
  backend/api.go
  backend/group.go
  backend/notification.go
Labels: enhancement

#83 revise database_test
  backend/database_test.go
Labels: enhancement

#85 Fix the CI build.
  backend/database.go
  backend/database_test.go
Labels: testing

#86 Create S3 and Route53 Terraform configurations
  terraform/route53.tf
  terraform/s3.tf
  terraform/variable.tf
Labels: enhancement

#87 Update third report.
  reports/20240207.md
Labels: documentation

#63 Mohamad DynamoDB, ACM, and CloudFront Terraform
  terraform/acm.tf
  terraform/cloudfront.tf
  terraform/dynamodb.tf
Labels: enhancement

#89 implemented update user and create message API
  backend/database.go
  backend/dbschema.go
Labels: enhancement

#90 Improve Terraform configurations.
  terraform/acm.tf
  terraform/cloudfront.tf
  terraform/dynamodb.tf
  terraform/lambda.tf
  terraform/s3.tf
Labels: enhancement

#91 Mohamad WebSocket (API Ggteway V2) Terraform configurations
  reports/20240207.md
  terraform/apigateway_rest.tf
  terraform/apigateway_ws.tf
  terraform/cloudfront.tf
  terraform/lambda.tf
  terraform/variable.tf
Labels: enhancement

#92 Update 3rd report.
  reports/20240207.md
Labels: documentation

#94 Design, implement, and test tasks API.
  backend/README.md
  backend/database.go
  backend/database_test.go
  backend/dbschema.go
  backend/group.go
  backend/group_task.go
  backend/main_test.go
  reports/20240207.md
Labels: enhancement

#95 Improve ID generation.
  backend/database.go
  backend/database_test.go
  backend/dbschema.go
  backend/group.go
  backend/group_activity.go
  backend/group_availability.go
  backend/group_task.go
  backend/notification.go
  backend/user.go
  reports/20240207.md
Labels: bug

#93 System integration.
  backend/database.go
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/Makefile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/+layout.ts
  frontend/src/routes/+page.svelte
  frontend/svelte.config.js
  terraform/apigateway_ws.tf
  terraform/cloudfront.tf
  terraform/route53.tf
Labels: enhancement

#100 Finalize 3rd report.
  reports/20240207.md
Labels: documentation

#101 Create 4th report from template.
  reports/20240214.md
Labels: documentation

#102 Backend sends notifications for all events
  backend/api.go
  backend/group.go
  backend/group_activity.go
  backend/group_availability.go
  backend/group_chat.go
  backend/group_poll.go
  backend/group_task.go
  backend/main_test.go
  backend/notification.go
  backend/user.go
  terraform/lambda.tf
Labels: enhancement

#104 Overhaul developer guides.
  README.md
  backend/Makefile
  backend/README.md
  frontend/Makefile
  frontend/README.md
  terraform/README.md
Labels: documentation

#105 Further improvements to developer guides/CI.
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/terraform.yml
  CONTRIBUTING.md
  README.md
  backend/Makefile
  backend/database.go
  frontend/.prettierignore
Labels: documentation

#103 Implement WebPush backend.
  backend/README.md
  backend/api.go
  backend/database.go
  backend/dbschema.go
  backend/go.mod
  backend/go.sum
  backend/main_test.go
  backend/notification.go
  backend/push.go
  terraform/dynamodb.tf
  terraform/lambda.tf
Labels: enhancement

#110 Update 4th report.
  reports/20240214.md
Labels: documentation

#111 Improve backend API documentation.
  backend/README.md
Labels: documentation

#113 WebSockets work in AWS.
  backend/api.go
  backend/database.go
  backend/dbschema.go
  backend/main.go
  terraform/dynamodb.tf
  terraform/lambda.tf
Labels: bug

#118 Update 4th report (part 2).
  reports/20240214.md
Labels: documentation

#123 daven status for 14Feb
  reports/20240214.md
Labels: documentation

#122 Test and improve backend.
  .github/CODEOWNERS
  backend/README.md
  backend/database.go
  backend/dbschema.go
  backend/group.go
  backend/group_activity.go
  backend/group_availability.go
  backend/group_chat.go
  backend/group_poll.go
  backend/group_task.go
  backend/main.go
  backend/main_test.go
  backend/notification.go
  backend/push.go
  backend/util.go
  backend/util_test.go
  terraform/dynamodb.tf
Labels: enhancement, testing

#124 Frontend integration
  frontend/src/lib/model.js
  frontend/src/lib/stores.js
  frontend/src/routes/+layout.ts
  frontend/src/routes/+page.svelte
  frontend/src/routes/dashboard/[groupId]/+page.svelte
  frontend/src/routes/dashboard/[groupId]/Chat.svelte
  frontend/src/routes/dashboard/[groupId]/PollCreationModal.svelte
  frontend/svelte.config.js
Labels: enhancement, refactor

#125 Enhance testing instructions in dev guide.
  CONTRIBUTING.md
  README.md
  frontend/Makefile
  reports/20240221.md
Labels: documentation

#126 Frontend and backend integration (chat)
  backend/api.go
  backend/database.go
  backend/main.go
Labels: enhancement

#127 Update 5th report.
  reports/20240221.md
Labels: documentation

#135 added new database APIs
  backend/database.go
Labels: enhancement

#134 Send push notification for chat.
  backend/README.md
  backend/group_chat.go
  backend/notification.go
  backend/push.go
Labels: enhancement

#136 Fix database bugs concerning the variable table.
  backend/database.go
Labels: bug

#140 Update 5th report.
  reports/20240221.md
Labels: documentation

#141 Add profanity filter.
  backend/go.mod
  backend/go.sum
  backend/group.go
  backend/group_chat.go
  backend/main_test.go
  backend/util.go
Labels: enhancement

#142 daven weekly report 21 Feb
  reports/20240221.md
Labels: documentation

#144 Add limit on data per user/group.
  backend/api.go
  backend/group.go
  backend/group_activity.go
  backend/group_availability.go
  backend/group_poll.go
  backend/group_task.go
  backend/util.go
Labels: bug

#152 Add API to get specific user.
  backend/README.md
  backend/main_test.go
  backend/user.go
  backend/util.go
Labels: enhancement

#156 Create 6th report.
  reports/20240228.md
Labels: documentation

#158 daven 28 feb status
  reports/20240228.md
Labels: documentation

#161 Update 6th report.
  reports/20240228.md
Labels: documentation
