Repository cse403-lemmeknow/lemmeknow, pull requests merged in 2024-01, with the labels that each got.

#3 Add pull request template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2 Add initial README.
  README.md
Labels: documentation

#1 Implement simple AWS Lambda REST microservice skeleton in Go.
  backend/.gitignore
  backend/Makefile
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: enhancement

#6 Add initial weekly status report and template.
  reports/20240124.md
  reports/TEMPLATE.md
Labels: documentation

#5 Add `CODEOWNERS` file.
  .github/CODEOWNERS
Labels: documentation

#4 Add layout, living document link to README.
  README.md
Labels: documentation

#7 Implement WebSocket event support.
  backend/main.go
Labels: enhancement

#10 Early Database Schema and Function Initialization
  backend/database.go
  backend/dbschema.go
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: enhancement

#9 Add simple backend test framework.
  backend/.gitignore
  backend/go.mod
  backend/go.sum
  backend/main.go
  backend/main_test.go
Labels: testing

#12 added weekly status report
  reports/20240124.md
Labels: documentation

#11 Add GitHub action for automated status checking
  .github/CODEOWNERS
  .github/workflows/build.yml
  README.md
  backend/database.go
  backend/dbschema.go
  backend/main.go
Labels: testing

#8 Implement Frontend Login Page draft
  frontend/.eslintignore
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.npmrc
  frontend/.prettierignore
  frontend/.prettierrc
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.js
  frontend/src/app.d.ts
  frontend/src/app.html
  frontend/src/index.test.js
  frontend/src/routes/+page.svelte
  frontend/src/routes/devteam.svelte
  frontend/src/routes/features.svelte
  frontend/src/routes/privacy.svelte
  frontend/static/cal.png
  frontend/static/calendar.png
  frontend/static/favicon.png
  frontend/static/highfive.png
  frontend/static/road.png
  frontend/static/roadtrip.png
  frontend/svelte.config.js
  frontend/tests/test.js
  frontend/vite.config.js
Labels: enhancement

#13 Update weekly status report.
  .github/CODEOWNERS
  reports/20240124.md
Labels: documentation

#14 Write team weekly status report.
  reports/20240124.md
Labels: documentation

#16 Modularize API, add draft session API.
  backend/api.go
  backend/main.go
  backend/session.go
Labels: refactor

#18 Added weekly status update & revise database code format
  backend/database.go
  backend/dbschema.go
  reports/20240124.md
Labels: documentation

#19 Modularize AWS services using mock-able interfaces.
  backend/database.go
  backend/dbschema.go
  backend/main.go
  backend/main_test.go
  backend/notification.go
Labels: testing, refactor

#22 Setup a directory for Terraform
  .github/workflows/terraform.yml
  README.md
  backend/.gitignore
  terraform/.gitignore
  terraform/Makefile
  terraform/README.md
  terraform/provider.tf
  terraform/variable.tf
Labels: enhancement

#23 Add second weekly report.
  reports/20240131.md
Labels: documentation

#24 Implement session API.
  backend/api.go
  backend/main.go
  backend/main_test.go
  backend/session.go
Labels: enhancement

#25 Fix README typo.
  terraform/README.md
Labels: documentation

#26 Add support for running backend on localhost.
  backend/Makefile
  backend/README.md
  backend/api.go
  backend/database.go
  backend/go.mod
  backend/go.sum
  backend/main.go
  backend/main_test.go
  backend/notification.go
  backend/session.go
Labels: enhancement

#27 Start implementing user and group API's.
  backend/README.md
  backend/api.go
  backend/database.go
  backend/go.mod
  backend/go.sum
  backend/group.go
  backend/main.go
  backend/main_test.go
  backend/user.go
Labels: enhancement, refactor

#28 Work on backend API's.
  .github/workflows/terraform.yml
  backend/README.md
  backend/api.go
  backend/database.go
  backend/group.go
  backend/group_chat.go
  backend/main.go
  backend/main_test.go
  backend/user.go
Labels: enhancement, refactor

#29 Design most other API's.
  .github/workflows/backend.yml
  backend/README.md
  backend/group.go
Labels: documentation

#30 Update API docs.
  backend/README.md
Labels: documentation

#32 More API redesigns (attempt 2).
  backend/README.md
Labels: documentation

#34 Update second report.
  reports/20240131.md
Labels: documentation

#33 Initial integration of backend and frontend.
  backend/README.md
  backend/api.go
  backend/dbschema.go
  backend/go.mod
  backend/go.sum
  backend/group.go
  backend/group_chat.go
  backend/main.go
  backend/main_test.go
  backend/user.go
  frontend/README.md
  frontend/src/lib/model.js
  frontend/src/routes/+page.svelte
Labels: enhancement

#35 Random refresh workaround.
  backend/README.md
  frontend/vite.config.js
Labels: bug, documentation

#39 Get started on Terraform configuration.
  terraform/.terraform.lock.hcl
  terraform/acm.tf
  terraform/apigateway_rest.tf
  terraform/apigateway_ws.tf
  terraform/cloudfront.tf
  terraform/dynamodb.tf
  terraform/eventbridge.tf
  terraform/iam.tf
  terraform/lambda.tf
  terraform/route53.tf
  terraform/s3.tf
Labels: enhancement

#42 Update 20240131.md
  reports/20240131.md
Labels: documentation
